ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "loyaltyEarnRatePaise" INTEGER NOT NULL DEFAULT 10000;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "loyaltyPointValuePaise" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "loyaltyMinRedeemPoints" INTEGER NOT NULL DEFAULT 500;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "loyaltyMaxRedeemPct" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "loyaltyExpiryDays" INTEGER NOT NULL DEFAULT 365;
